== C4 Modell

== C1 Architektur Diagram

- **Client-System**: Dies ist der Ort, an dem der Benutzer oder das System die Protokollmeldungen initiiert.
- **Protokollserver**: Ein System, das Protokollnachrichten vom Client empfängt und sie möglicherweise speichert oder verarbeitet.
- **Logger Common**: Eine gemeinsame Bibliothek oder ein Satz von Dienstprogrammen, die sowohl vom Client als auch vom Server verwendet werden, um die Protokollierung zu erleichtern.
- **Logger-Komponente**: Ein spezifisches Modul oder eine Komponente innerhalb des Client-Systems, das/die für das Senden von Protokollnachrichten verantwortlich ist.
- **Logger-Server**: Die serverseitige Anwendung, die eingehende Protokollnachrichten verarbeitet.

Mermaid Diagram Code:

[mermaid, format="svg", opts="inline"]
----
C4Context
  title System Context diagram for Logging System
  Enterprise_Boundary(eb, "Logging System") {
    Person(client, "Client", "User or system that initiates log messages.")
    System_Boundary(sb, "Client System") {
      System(loggerComponent, "Logger Component", "Module responsible for sending log messages.")
      System(loggerCommon, "Logger Common", "Shared library for logging functionalities.")
    }
    System(loggerServer, "Logging Server", "Receives and processes log messages.")

    Rel(client, loggerComponent, "Initiates log messages")
    BiRel(loggerComponent, loggerCommon, "Uses shared logging utilities")
    Rel(loggerComponent, loggerServer, "Sends log messages to")
  }
----

== C2 Container Diagram

[mermaid, format="svg", opts="inline"]
----
graph TB
    %% C2 Level - Container Diagram for DemoApp
    subgraph "Logging System"
        LoggerClient(Logger Client) -. "Implements" .-> LoggerInterface(Logger Interface)
        LoggerClient -- "RPC Calls" --> LoggerServer(Logger Server)
        LoggerServer -- "Uses" --> StringPersistor(String Persistor)
    end

    DemoApp(Demo App) -- "Uses" --> LoggerInterface

    classDef system fill:#e6e6e6,stroke:#333,stroke-width:2px;
    classDef container fill:#f9f,stroke:#333,stroke-width:1px;
    classDef external fill:#ff9,stroke:#333,stroke-width:1px;
    class LoggerInterface,LoggerCommon,LoggerServer,StringPersistor container;
    class DemoApp,LoggerClient system;
----